I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script2.rpy", line 5, in script
    stop bell
  File "renpy/common/000statements.rpy", line 263, in execute_stop_music
    renpy.music.stop(fadeout=eval(p["fadeout"]), channel=channel)
Exception: Audio channel u'bell' is unknown.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script2.rpy", line 5, in script
    stop bell
  File "renpy/ast.py", line 2015, in execute
    self.call("execute")
  File "renpy/ast.py", line 2003, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 263, in execute_stop_music
    renpy.music.stop(fadeout=eval(p["fadeout"]), channel=channel)
  File "renpy/audio/music.py", line 282, in stop
    c = get_channel(channel)
  File "renpy/audio/audio.py", line 912, in get_channel
    raise Exception("Audio channel %r is unknown." % name)
Exception: Audio channel u'bell' is unknown.

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
Among Us 2 fixed 1.0
Sun Mar 27 16:04:54 2022
